### ISSUE TITLE
Error while running server

### ISSUE THREAD

**Issue by radbrawler** [ashu1994/sampleGRPCvsREST#1]
I guess you need to change package import from `sampleGRPC/profile` to `github.com/ashu1994/sampleGRPCvsREST/profile` or `../profile` in  #`server.go`. When I do `go run server.go` it says
```
server.go:8:2: cannot find package "sampleGRPC/profile" in any of:
	/home/anmol.singh/apps/go/src/sampleGRPC/profile (from $GOROOT)
	/home/anmol.singh/go/src/sampleGRPC/profile (from $GOPATH)
```

**Comment by legacyshield** [comment]
ohh..I just realized that I changed the name of repository.Thanks.
